pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: test-odu
spec:
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
  containers:
  - name: jnlp
    image: 'jenkins/jnlp-slave:4.3-4-alpine'
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
  - name: maven
    image: maven:latest
    command:
    - cat
    tty: true
    imagePullPolicy: Always
    securityContext: # https://github.com/GoogleContainerTools/kaniko/issues/681
      runAsUser: 0
      runAsGroup: 0
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-1534f90c9330d40486136b2997e7972a79a69baf
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    volumeMounts:
      - name: regsecret
        mountPath: /kaniko/.docker
    securityContext: # https://github.com/GoogleContainerTools/kaniko/issues/681
      runAsUser: 0
      runAsGroup: 0
  volumes:
  - name: regsecret
    projected:
      sources:
      - secret:
          name: regsecret
          items:
            - key: .dockerconfigjson
              path: config.json
  imagePullSecrets:
  - name: regsecret
"""
    }
  }


  environment {
    
    /* -----------DevOps Commander  created env variables------------ */

DOCKER_URL= "us.icr.io/dc-tools"
DOCKER_CREDENTIAL_ID= "dc-docker-1749"
INSTANA_URL= "https://cas-ibmgbs.instana.io"
INSTANA_CREDENTIAL_ID= "dc-instana-1749"
LOGDNA_URL= "https://app.logdna.com"
LOGDNA_CREDENTIAL_ID= "dc-logdna-1749"
OCP_URL= "https://c100-e.au-syd.containers.cloud.ibm.com:31995"
OCP_CREDENTIAL_ID= "dc-ocp-1749"
SONARQUBE_URL= "https://sonarqube-1749-3725.dc-ig-lib-ga-1589529604-f72ef11f3ab089a8c677044eb28292cd-0000.au-syd.containers.appdomain.cloud"
SONARQUBE_CREDENTIAL_ID= "dc-sonarqube-1749"
CLAIR_URL= "clair-1749-3781-clair:6060"
CLAIR_CREDENTIAL_ID= "dc-clair-1749"
NAMESPACE= "dc-apps"
INGRESS= "dc-ig-lib-ga-1589529604-f72ef11f3ab089a8c677044eb28292cd-0000.au-syd.containers.appdomain.cloud"
    /* -----------DevOps Commander  created env variables------------ */

    DOCKER_IMAGE = readbuild.gradle().getArtifactId()
    // DOCKER_TAG = "$BUILD_NUMBER"
    DOCKER_TAG = readbuild.gradle().getVersion()
    componentName = readbuild.gradle()).getArtifactId()
    componentVersion = readbuild.gradle().getVersion()
  }
  stages {



    stage('Build: Application Package') {
      steps {
        container('gradle') {
              
              sh 'gradlew build'
              sh 'gradlew build -Dquarkus.package.type=uber-jar'
        }
      }
    }



  
		     






    stage ('Build: Docker') {
       steps {
           container('kaniko') {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIAL_ID}", usernameVariable: 'REGISTRY_USERNAME', passwordVariable: 'REGISTRY_PASSWORD')]) {
               /* Kaniko uses secret 'regsecret' declared in the POD to authenticate to the registry and push the image */
               sh '''
               mkdir -p /kaniko/.docker
               echo '{\"auths\":{\"'${DOCKER_URL}'\":{\"username\":\"'${REGISTRY_USERNAME}'\",\"password\":\"'${REGISTRY_PASSWORD}'\"}}}' > /kaniko/.docker/config.json
               cat /kaniko/.docker/config.json
               /kaniko/executor -f `pwd`/src/main/docker/Dockerfile.jvm -c `pwd` --insecure --skip-tls-verify --cache=true --destination=${DOCKER_URL}/${DOCKER_IMAGE}:${DOCKER_TAG}
              '''
                }
            }
         }
       }




   stage ('Secure: Image scan - Clair') {
       steps {
           container('openshift-cli') {
               withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIAL_ID}", usernameVariable: 'REGISTRY_USERNAME', passwordVariable: 'REGISTRY_PASSWORD')]) {
                   script {
                       catchError(buildResult: 'SUCCESS', stageResult: 'SUCCESS') { /* Avoid the stage being FAILURE if Clair founds vulnerabilities above acceptable threshold. That will be calculated later in the gate */
                         //  sh 'yair.py --clair ${CLAIR_URL} --registry ${REGISTRY_NAME} --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} --no-namespace ${DOCKER_IMAGE}:${DOCKER_TAG}'
    sh 'wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64'
    sh 'mv klar-2.4.0-linux-amd64 klar'
    sh 'chmod 755 klar'
                sh 'export CLAIR_ADDR=${CLAIR_URL} && export DOCKER_PASSWORD=${REGISTRY_PASSWORD} && export DOCKER_USER=${REGISTRY_USERNAME} && ./klar ${DOCKER_URL}/${DOCKER_IMAGE}:${DOCKER_TAG}  '
                       }
                   }
               }
           }
       }
       post {
           always {
               sh 'rm -rf $WORKSPACE/reports/clair && mkdir -p $WORKSPACE/reports/clair'
      //         sh 'cp clair-results.json $WORKSPACE/reports/clair'
           }
       }
   }



    stage('Deploy: To Openshift') {
        steps {
          container('openshift-cli') {
	     withCredentials([
	        usernamePassword(credentialsId: "${OCP_CREDENTIAL_ID}", usernameVariable: 'REGISTRY_USERNAME', passwordVariable: 'TOKEN'),
		      usernamePassword(credentialsId: "${DOCKER_CREDENTIAL_ID}", usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')
	     ]) {
              sh '''
              oc login --server="${OCP_URL}" --token="${TOKEN}"
              oc project ${NAMESPACE}
              pwd
              ls -ltr
              oc create secret docker-registry docker-repo-cred \
              --docker-server=${DOCKER_URL} \
              --docker-username=${DOCKER_USERNAME} \
              --docker-password=${DOCKER_PASSWORD} \
              --docker-email=${DOCKER_PASSWORD} \
              --namespace=${NAMESPACE} || true
              sed -e "s~{REGISTRY_NAME}~$DOCKER_URL~g" \
                  -e "s~{DOCKER_IMAGE}~$DOCKER_IMAGE~g" \
                  -e "s~{DOCKER_TAG}~$DOCKER_TAG~g" \
                  -e "s~{K8S_DEPLOYMENT}~$DEPLOYMENT_NAME~g" \
                  -e "s~{INGRESS_URL}~$INGRESS~g" -i devops/k8s/*.yml
              oc apply -f devops/k8s/ --namespace="${NAMESPACE}" || true
              oc delete pod --selector app=$DEPLOYMENT_NAME  || true
              oc create route edge --service=${DEPLOYMENT_NAME}-svc --hostname=$DEPLOYMENT_NAME.$INGRESS ||true
              oc wait --for=condition=available --timeout=120s deployment/${DEPLOYMENT_NAME} --namespace="${NAMESPACE}" || true
              '''
	     }
           }
         }
        }




    }
}

